### ISSUE TITLE
There is no class DaggerFunctionComponent

### ISSUE THREAD

**Issue by mnadeem** [kaibocai/azure-function-java-dependency-injection-samples#1]
There is no class DaggerFunctionComponent

**Comment by kaibocai** [comment]
Hi @mnadeem , thanks for reaching out as said in dagger offcial page 

> Dagger is a fully static, compile-time [dependency injection](http://en.wikipedia.org/wiki/Dependency_injection) framework for Java, Kotlin, and Android.

It's a static compile-time DI framework, which means you need to compile it first and add the genereated files to your source code folder to use them.
